metadb:
  host: 127.0.0.1
  port: 3306
  user: root
  password: **************1.
  base: chengken.starrocks_information_connections

server:
  port: 19321
  token: "123456"
  sshuser: starrocks
  loadhtmlglob: /u1/dlopsnas/chengken/templates/html/*.html
  loadstatic: /u1/dlopsnas/chengken/templates/static

schema:
  auditops:   #【选填】auditloader集成的审计日志表。
  whiteip:    #【选填】白名单ip，不需要输入token直接登入。
    - 10.14.5.198
log:
  path: '/u/users/svccndlopsns/chengken/log'

